import { Card } from './types';

export const mockCards: Card[] = [
  {
    id: 'dm-001',
    name: '轟く邪道 レッドゾーン',
    imageUrl: '/images/dm/dm25rp3-DM1.png',
    type: 'G-NEOドリーム・クリーチャー',
    civilization: '火',
    cost: 6,
    power: 12000,
    race: 'ソニック・コマンド/侵略者',
    effectText: 'D・D・D 火4\nG-NEO進化：闇、火、または自然のクリーチャー1体の上に置いてもよい。\nT・ブレイカー\nこのクリーチャーが出た時、アンタップする。\nこのクリーチャーが出た時または攻撃する時、相手の、パワーが一番小さいクリーチャーをすべて破壊する。\n自分のクリーチャーは、相手のカードによる攻撃できない効果を無視して攻撃できる。',
    zonesSupported: ['main'],
    rarity: 'DMR',
    set: 'DM25-RP3-01',
    cardNumber: 'DM1/DM1'
  },
  {
    id: 'dm-002',
    name: 'ボルメテウス・白銀の覇者',
    imageUrl: '/images/dm/bolmeteus.jpg',
    type: 'クリーチャー',
    civilization: '光',
    cost: 8,
    power: 12000,
    race: 'アーマロイド',
    effectText: 'ダブルブレイカー（このクリーチャーはシールドを2枚ブレイクする）\nこのクリーチャーは、相手プレイヤーを攻撃できない。\n相手のターン中、このクリーチャーは「ブロッカー」を得る。',
    zonesSupported: ['main', 'gr'],
    rarity: 'SR',
    set: 'DM-01',
    cardNumber: '002'
  },
  {
    id: 'dm-003',
    name: 'アレクローバー',
    imageUrl: '/images/dm/alecrover.jpg',
    type: 'クリーチャー',
    civilization: '自然',
    cost: 3,
    power: 2000,
    race: 'ワイルドベジーズ',
    effectText: 'パワーアタッカー+2000（攻撃中、このクリーチャーのパワーは+2000される）',
    zonesSupported: ['main'],
    rarity: 'C',
    set: 'DM-01',
    cardNumber: '003'
  },
  {
    id: 'dm-004',
    name: 'ドラゴン・ゾンビ',
    imageUrl: '/images/dm/dragon_zombie.jpg',
    type: 'クリーチャー',
    civilization: '闇',
    cost: 4,
    power: 4000,
    race: 'ドラゴン・ゾンビ',
    effectText: 'このクリーチャーがバトルゾーンを離れたとき、相手のマナゾーンからカードを1枚、相手の墓地に置く。',
    zonesSupported: ['main'],
    rarity: 'U',
    set: 'DM-01',
    cardNumber: '004'
  },
  {
    id: 'dm-005',
    name: 'ボルシャック',
    imageUrl: '/images/dm/bolshack.jpg',
    type: 'クリーチャー',
    civilization: '火',
    cost: 3,
    power: 3000,
    race: 'アーマード・ドラゴン',
    effectText: 'パワーアタッカー+1000（攻撃中、このクリーチャーのパワーは+1000される）',
    zonesSupported: ['main'],
    rarity: 'R',
    set: 'DM-01',
    cardNumber: '005'
  },
  {
    id: 'dm-006',
    name: 'コーリン',
    imageUrl: '/images/dm/corile.jpg',
    type: 'クリーチャー',
    civilization: '水',
    cost: 4,
    power: 2000,
    race: 'リキッド・ピープル',
    effectText: 'このクリーチャーがバトルゾーンに出たとき、カードを1枚引いてもよい。',
    zonesSupported: ['main'],
    rarity: 'U',
    set: 'DM-01',
    cardNumber: '006'
  },
  {
    id: 'dm-007',
    name: 'ジャスパー',
    imageUrl: '/images/dm/jaspar.jpg',
    type: 'クリーチャー',
    civilization: '光',
    cost: 4,
    power: 2000,
    race: 'ガーディアン',
    effectText: 'ブロッカー（相手クリーチャーが攻撃する時、このクリーチャーをタップして、その攻撃を阻止してもよい。その後、その相手クリーチャーとバトルする）',
    zonesSupported: ['main'],
    rarity: 'C',
    set: 'DM-01',
    cardNumber: '007'
  },
  {
    id: 'dm-008',
    name: 'ボルメテウス・黒龍の覇者',
    imageUrl: '/images/dm/bolmeteus_dragon.jpg',
    type: 'クリーチャー',
    civilization: '闇',
    cost: 8,
    power: 13000,
    race: 'アーマード・ドラゴン',
    effectText: 'ダブルブレイカー（このクリーチャーはシールドを2枚ブレイクする）\nこのクリーチャーがバトルに勝ったとき、相手のシールドを1枚見る。その後、それを山札の一番上か一番下に置く。',
    zonesSupported: ['main', 'gr'],
    rarity: 'SR',
    set: 'DM-01',
    cardNumber: '008'
  },
  {
    id: 'dm-009',
    name: 'ガトリング・スカサバー',
    imageUrl: '/images/dm/gatling_scissor.jpg',
    type: 'クリーチャー',
    civilization: '火',
    cost: 6,
    power: 4000,
    race: 'アーマード・ワイバーン',
    effectText: 'スピードアタッカー（このクリーチャーは召喚酔いしない）\nパワーアタッカー+2000（攻撃中、このクリーチャーのパワーは+2000される）',
    zonesSupported: ['main'],
    rarity: 'R',
    set: 'DM-01',
    cardNumber: '009'
  },
  {
    id: 'dm-010',
    name: 'ボルバルザーク・ドラゴン',
    imageUrl: '/images/dm/bolbalzak_dragon.jpg',
    type: 'クリーチャー',
    civilization: '火',
    cost: 7,
    power: 11000,
    race: 'アーマード・ドラゴン',
    effectText: 'ダブルブレイカー（このクリーチャーはシールドを2枚ブレイクする）\nこのクリーチャーが破壊されたとき、相手のマナゾーンからカードを2枚、相手の墓地に置く。',
    zonesSupported: ['main', 'gr'],
    rarity: 'SR',
    set: 'DM-01',
    cardNumber: '010'
  },
  {
    id: 'dm-011',
    name: 'ドルマゲドン',
    imageUrl: '/images/dm/dolmageidon.jpg',
    type: '城',
    civilization: '火',
    cost: 8,
    effectText: '【城ルール】このカードはドルマゲドンゾーンに置かれる。\n【起動】1ターンに1回、自分のターンの開始時に、自分の山札の上から1枚目をドルマゲドンゾーンに置いてもよい。\n【永続】自分のターンのはじめに、ドルマゲドンゾーンにカードが7枚以上あれば、ゲームに勝利する。',
    zonesSupported: ['dolmageidon'],
    rarity: 'R',
    set: 'DM-EX',
    cardNumber: 'EX-01'
  },
  {
    id: 'dm-012',
    name: '零龍',
    imageUrl: '/images/dm/zeroryu.jpg',
    type: 'クリーチャー',
    civilization: 'ゼロ',
    cost: 10,
    power: 20000,
    race: 'アーマード・ドラゴン',
    effectText: '【起動】このカードは通常の方法では召喚できない。自分のドルマゲドンゾーンにカードが7枚以上あるとき、このカードを自分の手札からコストを支払わずに召喚してもよい。\n【永続】このクリーチャーは「W・ブレイカー」を得る。（このクリーチャーはシールドを2枚ブレイクする）\n【永続】このクリーチャーは、すべての文明のシールドをブレイクする。',
    zonesSupported: ['zeroryu'],
    rarity: 'UR',
    set: 'DM-EX',
    cardNumber: 'EX-02'
  },
  {
    id: 'dm-013',
    name: '超次元ロボ ガイヤリュウ',
    imageUrl: '/images/dm/gaialord.jpg',
    type: 'クリーチャー',
    civilization: '光',
    cost: 7,
    power: 9000,
    race: 'アーマロイド',
    effectText: '【進化】- アーマロイド1体の上に置く。\n【永続】このクリーチャーは「W・ブレイカー」を得る。\n【起動】1ターンに1回、自分のターンのはじめに、バトルゾーンにある相手のクリーチャーを1体選び、タップしてもよい。',
    zonesSupported: ['main', 'gr'],
    rarity: 'R',
    set: 'DM-02',
    cardNumber: '023'
  },
  {
    id: 'dm-014',
    name: '超竜星神 アストロス',
    imageUrl: '/images/dm/astros.jpg',
    type: 'クリーチャー',
    civilization: '火',
    cost: 7,
    power: 10000,
    race: 'アーマード・ドラゴン',
    effectText: '【進化】- アーマード・ドラゴン1体の上に置く。\n【永続】このクリーチャーは「W・ブレイカー」を得る。\n【起動】1ターンに1回、自分のターンのはじめに、相手のシールドを1枚見てもよい。その後、それを元の場所に戻す。',
    zonesSupported: ['main', 'gr'],
    rarity: 'SR',
    set: 'DM-02',
    cardNumber: '024'
  },
  {
    id: 'dm-015',
    name: '超神星 バルガルザーク',
    imageUrl: '/images/dm/bargarzark.jpg',
    type: 'クリーチャー',
    civilization: '闇',
    cost: 7,
    power: 11000,
    race: 'デーモン・コマンド',
    effectText: '【進化】- デーモン・コマンド1体の上に置く。\n【永続】このクリーチャーは「W・ブレイカー」を得る。\n【起動】1ターンに1回、自分のターンのはじめに、相手の手札を1枚見ないで選び、捨てさせてもよい。',
    zonesSupported: ['main', 'gr'],
    rarity: 'SR',
    set: 'DM-02',
    cardNumber: '025'
  }
];
